### ISSUE TITLE
Option `strict` missing from per-event documentation

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/svgo-action#451]
# Documentation

## Description

The `strict` option (added in #436) is missing from [the events documentation](https://github.com/ericcornelissen/svgo-action/blob/f9c558da711d32e500141351bc5ab881b274bdb6/docs/events.md#svgo-action-events).

**Comment by Anubha13kumari** [comment]
hi @ericcornelissen  .first timer this side .i want to contribute on this issue please guide me .

**Comment by ericcornelissen** [comment]
Cool @Anubha13kumari :slightly_smiling_face: This issue is really quite straightforward, the `strict` option mentioned in the issue description needs to be added to each of the **Inputs** tables of the documentation linked in a consistent manner (formatted correctly and ordered alphabetically). The `strict` option is supported for all events and required for none.
