### ISSUE TITLE
Please update `v3` branch

### ISSUE THREAD

**Issue by krzema12** [ericcornelissen/svgo-action#784]
Hi, maintainer of https://github.com/typesafegithub/github-workflows-kt/ here!
I'd like to add first-class support for your action to the DSL. What's missing is updating the branch https://github.com/ericcornelissen/svgo-action/tree/v3 so that action-types.yml is included. Please let me know once done, I'll be glad to include your action. Alternatively, feel free to contribute to the library.

**Comment by ericcornelissen** [comment]
Thanks for reaching out @krzema12 :slightly_smiling_face: There's a release of [`v3`](https://github.com/ericcornelissen/svgo-action/tree/v3) scheduled for the 30th or later (2023-04-30). Most likely this release will happen the 1st (2023-05-01) or 2nd (2023-05-02) of next month.

I'll let you know here when that happened, until then I'll keep this issue open.

**Comment by ericcornelissen** [comment]
@krzema12 the `v3` branch has been updated, as of writing it points to the same commit as [v3.1.4](https://github.com/ericcornelissen/svgo-action/releases/tag/v3.1.4).

**Comment by krzema12** [comment]
https://github.com/typesafegithub/github-workflows-kt/pull/809
